services:
  design:
    container_name: hyvor-design
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./vite.config.js:/app/vite.config.js
      - ./tsconfig.json:/app/tsconfig.json
    labels:
      traefik.enable: true
      traefik.http.routers.hds.rule: Host(`design.hyvor.localhost`)
      traefik.http.routers.hds.entrypoints: https
      traefik.http.routers.hds.tls: true
      traefik.http.routers.hds.middlewares: vite-retry@file
      traefik.http.services.hds.loadbalancer.server.port: 36333
    networks:
      - hyvor-network

networks:
  hyvor-network:
    external: true
