services:
  hyvor-design:
    container_name: hyvor-design
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./static:/app/static
    labels:
      traefik.enable: true
      traefik.http.routers.hds.rule: Host(`design.hyvor.localhost`)
      traefik.http.routers.hds.entrypoints: https
      traefik.http.routers.hds.tls: true
      traefik.http.routers.hds.middlewares: vite-retry@file
      traefik.http.services.hds.loadbalancer.server.port: 36333
    networks:
      - hyvor-network

networks:
  hyvor-network:
    external: true
